# Generated by Django 4.0.4 on 2022-06-10 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='username',
            new_name='user',
        ),
    ]
