# Generated by Django 4.0.4 on 2022-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choose_rating',
            field=models.CharField(choices=[('1', 1), ('-1', -1)], max_length=50),
        ),
    ]
