# Generated by Django 4.0.4 on 2022-06-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vote',
            name='date_created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='time_created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
