# Generated by Django 4.0.4 on 2022-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_vote_created_at_vote_date_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='time_created_at',
        ),
        migrations.AlterField(
            model_name='vote',
            name='date_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
