# Generated by Django 4.0.4 on 2022-07-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatusermessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.publicchatroom'),
        ),
    ]
