# Generated by Django 4.0.4 on 2022-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Sum of calculated votes'),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Sum of calculated votes'),
        ),
        migrations.AddField(
            model_name='question',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Sum of calculated votes'),
        ),
    ]
