# Generated by Django 4.0.4 on 2022-06-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
