# Generated by Django 4.0.4 on 2022-06-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='question.tag', verbose_name='User`s tag(s)'),
        ),
    ]
