# Generated by Django 4.0.4 on 2022-06-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='username',
            new_name='user',
        ),
    ]
