# Generated by Django 4.0.4 on 2022-06-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_answer_user_alter_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
