# Generated by Django 4.0.4 on 2022-06-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='avatart',
            new_name='avatar',
        ),
    ]
