# Generated by Django 4.0.4 on 2022-06-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_comment_parent'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
        ('vote', '0001_initial'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
