# Generated by Django 4.0.4 on 2022-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userprofile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('NEW', 'New'), ('MIDL', 'Midl'), ('PRO', 'Pro'), ('STAFF', 'Staff')], default='NEW', max_length=40),
        ),
    ]
