# Generated by Django 4.0.4 on 2022-06-02 12:59

from django.db import migrations, models
import userapp.services


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_avatart_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to=userapp.services.upload_file),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
