# Generated by Django 4.0.4 on 2022-06-02 15:09

from django.db import migrations, models
import userapp.services


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_userprofile_avatar_alter_userprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=userapp.services.upload_file),
        ),
    ]
