# Generated by Django 4.0.4 on 2022-06-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rank_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Rank', 'verbose_name_plural': 'Ranks'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
